# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copy dependency dulu (biar cache kepake)
COPY go.mod go.sum ./
RUN go mod tidy

# Copy semua source code
COPY . .

# Build binary
RUN go build -o main .

# Run stage
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 3000

CMD ["./main"]